# Generated by Django 5.2.7 on 2025-10-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CecypharmFirstCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_category_cecypharm_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_category_cecypharm_description', models.TextField()),
                ('first_category_cecypharm_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('first_category_cecypharm_image', models.FileField(upload_to=' first_image/')),
                ('first_category_cecypharm_publish_date', models.DateTimeField(auto_now_add=True)),
                ('first_category_cecypharm_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_category_cecypharm_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='MainImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cecypharm_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cecypharm_description', models.TextField()),
                ('cecypharm_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('cecypharm_image', models.FileField(upload_to='main_image/')),
                ('cecypharm_publish_date', models.DateTimeField(auto_now_add=True)),
                ('cecypharm_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cecypharm_publish_date'],
            },
        ),
    ]
