# Generated by Django 5.2.7 on 2025-10-31 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_cypharm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CecypharmSecondCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_category_cecypharm_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_category_cecypharm_description', models.TextField()),
                ('second_category_cecypharm_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('second_category_cecypharm_image', models.FileField(upload_to=' second_image/')),
                ('second_category_cecypharm_publish_date', models.DateTimeField(auto_now_add=True)),
                ('second_category_cecypharm_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-second_category_cecypharm_publish_date'],
            },
        ),
    ]
