# Generated by Django 5.2.7 on 2025-11-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_cypharm', '0002_cecypharmsecondcategoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('author', models.CharField(default='Ce-cypharm', max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
