# Generated by Django 5.2.7 on 2025-10-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_cypharm', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cecypharm_author',
        ),
    ]
