# Generated by Django 5.2.7 on 2026-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_cypharm', '0005_alter_category_options_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecypharmfirstcategoryimage',
            name='first_category_cecypharm_image',
            field=models.FileField(upload_to='first_image/'),
        ),
        migrations.AlterField(
            model_name='cecypharmsecondcategoryimage',
            name='second_category_cecypharm_image',
            field=models.FileField(upload_to='second_image/'),
        ),
    ]
